CREATE TABLE CITIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE SPECIALITIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE DOCTOR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    gender ENUM('Male','Female','Other') NOT NULL,
    AGE INT,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    CITY_ID INT,
    SPECIALITY_ID INT,
    INSTITUTE_NAME VARCHAR(150),
    DEGREE_NAME VARCHAR(150),
    YOE INT,
    CONSULTATION_FEE DECIMAL(10,2),
    PROFILE_PICTURE TEXT,
    SEARCH_COUNT INT DEFAULT 0,
    FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL,
    FOREIGN KEY (speciality_id) REFERENCES specialities(id) ON DELETE SET NULL
);